# -*- coding: utf-8 -*-
"""Copy of Copy of Assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fZeXDO6LxEWh4lL3XbLK-_pj4ANgNH3z
"""

# create a simple calculator

a=int(input("enter the first value"))
b=int(input("enter the second value"))
c=str(input("add,sub,mul,div"))
if c=="add":
  print(a+b)
elif c=="sub":
    print(a-b)
elif c=="mul":
    print(c*b)
else:
    print(a/b)

a=int(input("enter the first value:"))
b=int(input("enter the second value:"))
print("addition of two numbers",a+b)
print("subtraction of two numbers",a-b)
print("multiplication of two numbers",a*b)
print("division of two numbers",a/b)